### ISSUE TITLE
It does not work with the Huawei P8 Lite 2017 

### ISSUE THREAD

**Issue by Papill0n** [SkyEmie/huawei-honor-unlock-bootloader#100]
I tried the program with my Huawei P8 Lite 2017 (PRA-LX1 8.0.0.392 (C02); EMUI VERSION 8.0.0; ANDROID VERSION 8.0.0) and it doesn't work. Five days of fruitless attempts. Can anyone explain to me why? @SkyEmie @programminghoch10

**Comment by LightHouseGaming** [comment]
@Papill0n Use Potato NV, I Used It a Few Months Ago As An Alternative On Another Device, It Works Granted Its More Hands On

![image](https://user-images.githubusercontent.com/49514654/151678547-afa5f8f2-e55f-4f5e-bd30-fb0d337c797d.png)
