### ISSUE TITLE
Honor 8 unsuccessful

### ISSUE THREAD

**Issue by Nuc1eoN** [SkyEmie/huawei-honor-unlock-bootloader#101]
```
Bruteforce is running...
Currently testing code 9999970521927710
Progress: 100.0%
FAILED (remote: 'check password failed!')
fastboot: error: Command failed

OEM Code not found!
```
So after 100% and rebooting about a milliion times, the code was not found on my Honor 8 FRD-09 8.0.0.521 (C432).

Since they also made it impossible to downgrade from this firmware version (2018 july security patch), I suppose they patched something in the bootloader (maybe switched to alphanumeric) to make brueforcing unsucssessful.

**Comment by FBIAgent05** [comment]
May I ask how long it took to get to 100%?

**Comment by Nuc1eoN** [comment]
About 3 days
