### ISSUE TITLE
FYI: This repo was stolen from you and re-uploaded with an malware infected AdbWinApi.dll

### ISSUE THREAD

**Issue by dhuit90** [SkyEmie/huawei-honor-unlock-bootloader#103]
https://github.com/Chernobylll/Huawei-unlock-bootloader

https://www.virustotal.com/gui/file/fcc0a11c62d1a4c87d0857416aaac29f4f8e06c19c265da4579741a7c3c6ea0c?nocache=1

**Comment by AnonymousDebug** [comment]
GitHub has taken that repository offline. 
Thank you.
