### ISSUE TITLE
Unexpected EOF while parsing

### ISSUE THREAD

**Issue by GenkiGitHub** [SkyEmie/huawei-honor-unlock-bootloader#105]
Trying to unlock Huwaei P8 lite 2017 (PRA-LX1), and I get this when I press "enter to reboot the device.

<img width="476" alt="Screenshot 2021-12-08 at 22 42 44" src="https://user-images.githubusercontent.com/36342349/145281648-b2b318cf-5d8f-45b7-9e88-cbb2dd191408.png">
"

**Comment by MouseMoosz** [comment]
Please do **NOT** share your IMEI number in public.
As for the issue, please try re-cloning the repository, the files may have been damaged.
