### ISSUE TITLE
Requires confirmation for each attempt

### ISSUE THREAD

**Issue by RisingArmechadon** [SkyEmie/huawei-honor-unlock-bootloader#106]
Im not sure how to fix this, it needs me to press yes each attempt.

**Comment by MouseMoosz** [comment]
What do you mean by "attempt"? Every time you start the script or every code the script tries?

If you mean everytime the script starts, in `unlock.py` replace 0 `staticimei = 0`  with your IMEI number and replace False `quickstart = False` with True.

**Comment by aic69420** [comment]
I have the same issue as I have a Huawei Y6 2019 and the phone asks to confirm using the volume buttons
