### ISSUE TITLE
Is it going right for me?

### ISSUE THREAD

**Issue by j-brake** [SkyEmie/huawei-honor-unlock-bootloader#13]
Thanks for the code!
I have entered the IMEI and the program seems to be running, the following messages keep appearing:
FAILED (remote: 'Invalid key, unlock fail')
fastboot: error: command failed
FAILED (remote: 'Invalid key, unlock fail')
fastboot: error: command failed
.
.
.
It's been going on for about two days now, should I keep waiting? Or is it useless?
By the way, I have a Honor 5x

**Comment by TG310** [comment]
Does the messages appear slow and consistently or it is spamming rapidly?

**Comment by j-brake** [comment]
I would say the messages spam fast and consistently ;-)

**Comment by TG310** [comment]
I think you are on the right way.
but 2 days straight is enough time to run through all the possible numbers
(I had only ran it for 12 hours but its already half the way)
I think its useless for you now.

If you want to try your luck then why don't you try this:
https://github.com/Martazza/Huawei-Bootloader-Unlocker
