### ISSUE TITLE
The unlock code is region relevant?

### ISSUE THREAD

**Issue by YijunYuan** [SkyEmie/huawei-honor-unlock-bootloader#23]
As @lubagov mentioned [here](https://github.com/Martazza/Huawei-Bootloader-Unlocker/issues/5#issuecomment-627417651):

> Codes for Chinese regione phones is numeric. Phor tablet for diffirent countyes it contain all alphabete

So I wonder if this program works only for the region other than China or the opposite?

**Comment by SkyEmie** [comment]
Hi, I could only test on European models (as indicated in the readme) and yep, the bootloaders of others regions are different, and I have no idea how the ones in the other regions work
