### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by pApY-Dalix** [SkyEmie/huawei-honor-unlock-bootloader#28]
Hello, I'm trying the script on my Honor 8X, after following the instructions given, an error occurs after restarting the smartphone... Here's what the terminal looks like :
```
                                                   FAILED (remote: 'invalid command')
fastboot: error: Command failed
                                                   FAILED (remote: 'invalid command')
fastboot: error: Command failed
...
```
Can you tell me where the error came from, thank you very much.

**Comment by pApY-Dalix** [comment]
After a new attempt, the terminal to indicate this in addition to the previous error :
```
Traceback (most recent call last):
  File "unlock.py", line 79, in <module>
    codeOEM = tryUnlockBootloader(checksum)
  File "unlock.py", line 24, in tryUnlockBootloader
    sdrout = str(os.system('fastboot oem unlock '+str(algoOEMcode)))
```

**Comment by nazariiixa** [comment]
I have the same problem "fastboot: error: Command failed
                                                                                  FAILED (remote: 'invalid command')" for all atempt, with my Honor view 20

**Comment by pApY-Dalix** [comment]
I think the error comes from the ADB and not from the python script, or a mix between the two :/

**Comment by Jok00er** [comment]
I have the same problem with my Huawei y9 prime 2019. My computer is running on windows 10

**Comment by 24kcsplus** [comment]
I have the same problem with my honor 9x China version......

**Comment by Remty5** [comment]
"fastboot: error: Command failed FAILED (remote: 'invalid command')"
Is absolutely normal, that's the output of fastboot when the unlock code is wrong, that's why this program searches for it, it should find it eventually.
