### ISSUE TITLE
Linux support 

### ISSUE THREAD

**Issue by advaithm** [SkyEmie/huawei-honor-unlock-bootloader#3]
@SkyEmie I would like to make a Linux port so I was wondering if you would allow me to do this. I would like to publish the port on the main github

**Comment by SkyEmie** [comment]
You can if you wish :)

**Comment by ClashLuke** [comment]
@advaithm installing adb/fastboot is all you need. Try running `sudo add-apt-repository ppa:nilarimogard/webupd8 && sudo apt-get update && sudo apt-get install android-tools-adb android-tools-fastboot` to get the clis. ([source](http://www.webupd8.org/2012/08/install-adb-and-fastboot-android-tools.html))
