### ISSUE TITLE
How long will it take to get the right code?

### ISSUE THREAD

**Issue by nICEnnnnnnnLee** [SkyEmie/huawei-honor-unlock-bootloader#34]
Write the time you spent pls...
I'm considering whether to buy a code or not.

**Comment by nICEnnnnnnnLee** [comment]
Well, I give it up...
I have tried algoOEMcode from 1000000000000000(16 digits) to 10078719127057140(17 digits), unfortunately I didn't hit the code.

**Comment by nICEnnnnnnnLee** [comment]
I'm not sure whether the head and every step of brute force is appropriate,  
but the right algoOEMcode of mine just begin with 0 and less than 1000000000000000 since it was unlocked using command: 
```
fastboot oem unlock 060082931962**** (use * instead for privacy)
```
BTW, my device : Honor 7(PLK-TL01H)

**Comment by lokkiii** [comment]
@nICEnnnnnnnLee that is awesome news. Congrats!  Btw, did you use the same code that SkyEmie had provided, or have you used another code of your own pls. Kindly let us know as many are struggling since 1 or 2yrs to find a break in this matter...

Thank you...

**Comment by David-H-1** [comment]
Newer devices use 16 alphanumeric codes which is 36^16=7958661109946400884391936 possibilities. With some models rebooting every 5 failed attempts, it will take decades to unlock newer models.
