### ISSUE TITLE
Error messages "Navigate to developer options, and enable OEM unlock"

### ISSUE THREAD

**Issue by bantour** [SkyEmie/huawei-honor-unlock-bootloader#35]
Is this the normal operation of the program? Is this how it should be?
![image](https://user-images.githubusercontent.com/29666914/84237394-931dbe00-aaf9-11ea-829c-cb75b55ae879.png)

**Comment by Jppx** [comment]
This seems to happen after around an hour of search through the permutations. I have to reboot the phone to normal, then start the process again at the latest code. (If it happen right away, you maybe dont have the OEM Unlock option enabled on the handset. (System & Updates >> Developer Options >> Enable OEM Unlock)

**Comment by bantour** [comment]
I get this message immediately when I run the script. Thе option "Enable OEM Unlock" is enabled.

**Comment by Jppx** [comment]
I only get that message after around 1 hour in fastboot mode. During that hour I get the standard ' FAILED (remote: 'invalid command') repeated for every attept at the code.
On your phone screen in FastBoot Mode does the 'FRP Unlock' message in red appear?

**Comment by bantour** [comment]
![0](https://user-images.githubusercontent.com/29666914/85928276-0ff7b880-b8ac-11ea-80c7-f4716a87ba3a.jpg)

**Comment by Jppx** [comment]
You may have to take off the FRP lock then.  I think it involves removing the google account from the phone. Check online - I seen a procedure for this a while back.

**Comment by Jppx** [comment]
I have PHONE Locked  (Green)
          FTP Unlock  (Red)
