### ISSUE TITLE
how to fix this error?

### ISSUE THREAD

**Issue by relex458** [SkyEmie/huawei-honor-unlock-bootloader#37]
**the following messages keep appearing rapidly, whilst the bootmenu is refreshing**:
                                                   FAILED (remote: 'check password failed!')
fastboot: error: Command failed
                                                   FAILED (remote: 'check password failed!')
fastboot: error: Command failed
                                                   FAILED (remote: 'check password failed!')
fastboot: error: Command failed
                                                   FAILED (remote: 'check password failed!')
fastboot: error: Command failed
Rebooting into bootloader                          OKAY [  0.021s]
Finished. Total time: 0.023s

**Comment by relex458** [comment]
also: this was already asked (#14 ), but no one answered

**Comment by yerbestpal** [comment]
Isn't this just the message displayed as it fails brute-force tries? I hope so, because I have had it running in this fashion for over an hour now.

**Comment by Remty5** [comment]
Well yeah that's the output of the fastboot oem unlock command when you provide the wrong unlock code, which this program tries to find, so of course it's gonna try hundreds of them.
@relex458 please close thus issue.

**Comment by emha-koeln** [comment]
Hi,
see [14](https://github.com/SkyEmie/huawei-honor-unlock-bootloader/issues/14)
