### ISSUE TITLE
Doesnt Find Code for Honor View 10 (UK)

### ISSUE THREAD

**Issue by Jppx** [SkyEmie/huawei-honor-unlock-bootloader#39]
Model: Honor View 10 (BKL-L09)
EMUI: 10.0.0.177 (C432E4R1P4)  
Country: UK

Ran through all permutations based on the algorithm (including values below 15 digits). This took around 12 hours total.
**No unlock code found**. So it may be true that after EMUI 10, there is no way to unlock the bootloader on Hauwei phones.

**Comment by TipzTeam** [comment]
I feel like downgrading to Oreo before the June patch should do the trick.

**Comment by Jppx** [comment]
Can't downgrade from Android 10, because I cant unlock the bootloader.  - Catch 22.

**Comment by TipzTeam** [comment]
No, you could use the SD downgrade method.

**Comment by lokkiii** [comment]
Is there any tutorial you can point to? Probably on youtube, or can you please write down the steps and help, of how can we achieve it without the bootloader unlocked please?

**Comment by TipzTeam** [comment]
> @TipzTeam Is there any tutorial you can point to? Probably on youtube, or can you please write down the steps and help, of how can we achieve it without the bootloader unlocked please?
> 

Searching online will be your answer.

**Comment by llight3** [comment]
This is prabably because the EU region used alpha numeric, try the random approach

**Comment by sohail4k** [comment]
Downgrading to EMUI 9 from higher  does not require bootloader unlcok ,   just need to download the right files    for dload mode in recovery . and there you go

**Comment by g-a-b-r-i-e-l** [comment]
> Can't downgrade from Android 10, because I cant unlock the bootloader. - Catch 22.

So, connect your phone with a cable to your pc, install hisuite on it, then configure it and connect your phone using hisuite, there sould be a button that says update, click on it, wait and there should be a button that says switch to other version or something, press on it and do what it wants you to do for the downgrade. **WARNING: IT WILL ERASE ALL OF YOUR DATA!!!**
