### ISSUE TITLE
Application doesn't launch.

### ISSUE THREAD

**Issue by Dino-dynamite** [SkyEmie/huawei-honor-unlock-bootloader#4]
When i connect my huawei p10 phone in usb debugging mode none of the applications work.
They all launch and then they shut down immediately. I have downloaded the adb drivers and python.
If i am doing something wrong please tell me.

**Comment by Ajsyl** [comment]
Delete 1st line in script

**Comment by SkyEmie** [comment]
I've already seen on Windows 10 that python was replaced by a launcher in the path, which redirects to the windows store. Normally the comment on the first line is ignored, I don't see any other cause.
