### ISSUE TITLE
Info:My huawei mate 10 C432 unlock code 

### ISSUE THREAD

**Issue by P82maarj** [SkyEmie/huawei-honor-unlock-bootloader#47]
I get my unlock code QBH8BN4P8U2WT13W before huawei locked it. This is my code and phone info. Hope it could help

sn:2WT7N18117002263
imei:866216031177475
PRODUCTID:33477519
Your unlocking password is: QBH8BN4P8U2WT13W

Phone information:
SN:2WT7N18117002263
IMEI:866216031177475
IMEI1:866216031177475
MEID:A000008475529D

Lock state info:
FB LockState: LOCKED
USER LockState: UNLOCKED

Current build number:
ALP-L09 8.0.0.132(C432)

Product model:
ALP-L09

**Comment by SkyEmie** [comment]
Hi, what is the region of your phone? Europe? Asian? China?

**Comment by P82maarj** [comment]
Europe.
Regards
