### ISSUE TITLE
FAILED (remote: 'Invalid key,unlock fail, error num: 7')

### ISSUE THREAD

**Issue by G3NG4RNL** [SkyEmie/huawei-honor-unlock-bootloader#48]
hey guys, is this normal?

its running now and i can see in the title bar its trying all different kind of codes but i can not find the meaning of error num 7
is it running like it should?

thanks!

![image](https://user-images.githubusercontent.com/69095820/89113166-ca5f7a00-d46d-11ea-8d2e-8dfdc0d01b32.png)

**Comment by StendhalSyndrome** [comment]
I think it's normal.
