### ISSUE TITLE
Any ideas for wifi tablets?

### ISSUE THREAD

**Issue by nayavu** [SkyEmie/huawei-honor-unlock-bootloader#5]
I have MediaPad T5 AGS2-W09 (wifi) which obviously does not have IMEI, but has MAC instead.
Any ideas how to adopt your brute force method for wifi devices? The only thing I can think of is to convert MAC into a long int and to try the same algorithm but not sure if it makes any sense.

**Comment by 3c71** [comment]
Same here, got a M3 Lite BAH-W09 (wifi) with no IMEI.

**Comment by 3c71** [comment]
Here it said that Antutu was providing the IMEI on wifi tablets. So I tried and got a PFSNU number, the same one I gave Huawei a couple of years ago asking for the unlock code (which they provided but didn't work at all).

This is the same ID I get when connected to ADB, and the same ID that can be found in about tablet, state, serial number.

However it's only 11 digits, after the 'PFSNU'. So I'll be trying to use those adding 3 leading 0s to make it 15 digits. 

It's running now, no idea how long it'll take or if it will succeed. Worth a shot though.

**Comment by nayavu** [comment]
Any luck with it?

**Comment by 3c71** [comment]
It did 1% in 5 hours, so I gave up as no-one appears to confirm it works.

**Comment by dcosta72** [comment]
any progress on this? I'm on the same boat on a T3 AGS-W09...

**Comment by SkyEmie** [comment]
For tablets, I don't know if the bootloader is the same like phone I can't test this :/
