### ISSUE TITLE
Add an Instructions

### ISSUE THREAD

**Issue by bagou4502** [SkyEmie/huawei-honor-unlock-bootloader#59]
Hello
in Instructions add this

Enable OEM unlock

because on Honor 9 if this option is not enable i got command invalid

**Comment by GivouDev** [comment]
This is right on the start of the script....!!!
Read:
print('\n\n           Unlock Bootloader script - By SkyEmie_\' and programminghoch10')
print('\n\n  (You must enable USB DEBUGGING and OEM UNLOCK in the developer options of the target device...)')
print('  !!! All data will be erased !!! \n')



LG
