### ISSUE TITLE
< waiting for any device >                                                    FAILED (remote: 'invalid command')

### ISSUE THREAD

**Issue by AzuKaOwO** [SkyEmie/huawei-honor-unlock-bootloader#62]
Bruteforce is running...
Currently testing code 1000000000000000
Progress: 10.0%
< waiting for any device >
                                                   FAILED (remote: 'invalid command')
fastboot: error: Command failed

Could not parse output.
Please check the output above yourself.
If you want to disable this feature, switch variable unknownfail to False

C:\Users\MY_PC\huawei-honor-unlock-bootloader>

**Comment by SlowLogicBoy** [comment]
`failmsg = "invalid key,unlock fail"   #used to check if code is wrong`

**Comment by programminghoch10** [comment]
Read the damn FAQ
