### ISSUE TITLE
huawei honor 9x 

### ISSUE THREAD

**Issue by yjj2002** [SkyEmie/huawei-honor-unlock-bootloader#66]
huawei honor 9x 
Bruteforce is running...
Currently testing code 1000000000000000
Progress: 10.0%
< waiting for any device >
...

FAILED (remote: Command not allowed)
finished. total time: 0.011s

Could not parse output.
Please check the output above yourself.
If you want to disable this feature, switch variable unknownfail to False

**Comment by JamiKettunen** [comment]
I suggest [reading the instructions](../#instructions). If OEM unlocking and USB debugging are already enabled and attempting to run `fastboot oem unlock XXXXXXXXXXXXXXXX` causes that output, your device likely simply blocks unlocking the bootloader altogether and there is nothing you can do (other than not buying a Huawei next time).

**Comment by programminghoch10** [comment]
@JamiKettunen 
Nah he probably forgot to downgrade, yet another time that people don't read the FAQ.
Or he actually didn't enable OEM unlock.
You see how he renamed the issue? It's probably the first.
