### ISSUE TITLE
Is this software even guaranteed to work in any way?

### ISSUE THREAD

**Issue by NO111ONE** [SkyEmie/huawei-honor-unlock-bootloader#70]
Has anyone had ANY luck with it?
Was it possible to get to the boot loader unlock screen for anyone using this?

**Comment by SkyEmie** [comment]
Hi,
It may not work every time, depending on the version of the bootloader, region. But it works fortunately yes, I let you look at the number of people who liked or fork this script 😉

**Comment by NO111ONE** [comment]
Oh, ok, got it, so there is a chance we'll find the code. Well, I decided
to use SigmaKey already

**Comment by nicholasostman** [comment]
can close this issue

**Comment by NO111ONE** [comment]
Forgot to do that. Thanks for reminding.
_Using SigmaKey, basically unlimited HCU client_
