### ISSUE TITLE
Any solution for tablets with no IMEI number?

### ISSUE THREAD

**Issue by potyt** [SkyEmie/huawei-honor-unlock-bootloader#72]
I tried using the Serial Number, but it is alphanumeric, not just numeric. Any other ideas?

I've kicked it off, having hacked it to use an increment of 1, not got a lot of hope that this will finish in my lifetime!

**Comment by Cicango** [comment]
Have you looked on the box from tablet, maybe there is a number that could look like an IMEI?

**Comment by potyt** [comment]
Can't see anything. Just a serial number, but that doesn't work. Nothing visible in settings on the device either.
Do we actually have any confirmation this works for devices with an IMIEI number anyway?

**Comment by Cicango** [comment]
Have u tried to go under settings>about phone/tablet and find a number similar to an IMEI?

**Comment by programminghoch10** [comment]
@potyt
You can use random codes, check #54
