### ISSUE TITLE
algorithm

### ISSUE THREAD

**Issue by deneb2** [SkyEmie/huawei-honor-unlock-bootloader#77]
**EDIT:** sorry I wrote in Italian before

As far as I understand, the assumption here is that the unlock code is within `1000000000000000 + (N * int(sqrt(imei)*1024)`.
So this software is scanning all the possible value of `N`.

How did you find this algorithm? I found some codes online and it looks like they do not follow this rule.

**Comment by irsl** [comment]
Yeah. This looks like a prank.

**Comment by programminghoch10** [comment]
@deneb2
This question has been asked for a long time.
You can find a lot of IMEI / SN / Code combinations in #52 
Try your best and find a better one.
