### ISSUE TITLE
Stuck on "testing code 10000000000000"

### ISSUE THREAD

**Issue by iNiKKo** [SkyEmie/huawei-honor-unlock-bootloader#79]
Hey so i just want to know if it's supposted to look like this or if it means that it doesn't work

![image](https://user-images.githubusercontent.com/67593147/108517223-0e598580-72bf-11eb-99ea-c9d20a5312f3.png)

**Comment by llight3** [comment]
Should be fixed by running as root in linux

**Comment by dlgames2013** [comment]
how to fix it in Windows?

**Comment by llight3** [comment]
No clue how to fix it in windows also this way of doing it is basically impossible nowadays have a read of some of the other isuess, your better off using potato NV if that works if u have a newish phone

**Comment by Naozumi520** [comment]
I fix it with a really weird way, It is because of the driver didn't install correctly or even installed on ur pc!
to do this u'll need the adb installer:
https://forum.xda-developers.com/attachment.php?attachmentid=4623157&d=1540039037
after unzip it just open the exe installer, type "Y" in all options, then u'll got the driver....... u'll got nothing install!
Then I use 7zip to unzip the exe installer, inside the installer there's a folder call "driver" with a file "android_winusb.inf"
Go to the windows device manager, there should have a device call "HIxxxx" (mine was "HI3650"),  manually update the driver with that "android_winusb.inf" driver, then u'll got the Android Bootloader Interface driver installed!
after that just try the unlock program agin.

**Comment by Edermg05** [comment]
> I fix it with a really weird way, It is because of the driver didn't install correctly or even installed on ur pc!
> to do this u'll need the adb installer:
> https://forum.xda-developers.com/attachment.php?attachmentid=4623157&d=1540039037
> after unzip it just open the exe installer, type "Y" in all options, then u'll got the driver....... u'll got nothing install!
> Then I use 7zip to unzip the exe installer, inside the installer there's a folder call "driver" with a file "android_winusb.inf"
> Go to the windows device manager, there should have a device call "HIxxxx" (mine was "HI3650"), manually update the driver with that "android_winusb.inf" driver, then u'll got the Android Bootloader Interface driver installed!
> after that just try the unlock program agin.

Where is the device supposed to be? Cause I have unzipped everything as you said, and it has worked, but when I go to device manager, I can see a "Android Phone" but nothing similar to "HIxxxx".
I hope you can help me.

**Comment by Naozumi520** [comment]
> > I fix it with a really weird way, It is because of the driver didn't install correctly or even installed on ur pc!
> > to do this u'll need the adb installer:
> > https://forum.xda-developers.com/attachment.php?attachmentid=4623157&d=1540039037
> > after unzip it just open the exe installer, type "Y" in all options, then u'll got the driver....... u'll got nothing install!
> > Then I use 7zip to unzip the exe installer, inside the installer there's a folder call "driver" with a file "android_winusb.inf"
> > Go to the windows device manager, there should have a device call "HIxxxx" (mine was "HI3650"), manually update the driver with that "android_winusb.inf" driver, then u'll got the Android Bootloader Interface driver installed!
> > after that just try the unlock program agin.
> 
> Where is the device supposed to be? Cause I have unzipped everything as you said, and it has worked, but when I go to device manager, I can see a "Android Phone" but nothing similar to "HIxxxx".
> I hope you can help me.

Maybe it's cuz my phone cpu is kirin and your device is qualcomm? .
Basically it's the same. both are under the adb mode.
Can you try to manually install the device with the"android_winusb.inf"?
It should work just fine.
Good luck!
