### ISSUE TITLE
honor lite 9

### ISSUE THREAD

**Issue by mr-1024** [SkyEmie/huawei-honor-unlock-bootloader#80]
How many people can unlock successfully

**Comment by mr-1024** [comment]
For a while
> Could not parse output.
> Please check the output above yourself.
> If you want to disable this feature, switch variable unknownfail to False

**Comment by sergeyzapor** [comment]
I suppose nobody. May be I am wrong.

**Comment by llight3** [comment]
You may be able to use https://github.com/mashed-potatoes/PotatoNV this approach doesnt look like its going to work any more
