### ISSUE TITLE
Fix for USB issues (too many links)

### ISSUE THREAD

**Issue by nine9999** [SkyEmie/huawei-honor-unlock-bootloader#84]
Might be useful for someone with only USB 3.0 ports in their PC to deal with FAILED (Status read failed (Too many links)) errors;

Paste this before the line "if 'reboot' in output:"
```
        if 'too many links' in output:
            print("USB communications error.  Retrying.")
            continue
```

**Comment by funtastian** [comment]
i had the same error, but fixed it by adding a small sleep timer in line 70 **time.sleep(1)**
