### ISSUE TITLE
Stuck on Reboot (10%) , Nova 5T

### ISSUE THREAD

**Issue by alexschultze** [SkyEmie/huawei-honor-unlock-bootloader#89]
The brute force does not start.

`Bruteforce is running...
Currently testing code 1000000000000000
Progress: 10.0%
`

The phone is rebooted and shows "fastboot&rescue mode".

**Comment by alexschultze** [comment]
I can extend the following. Simply running the fastboot command is stuck:

'fastboot oem unlock 100000000000
< waiting for any device >'

**Comment by Naozumi520** [comment]
#79
