### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by DAMcraft** [SkyEmie/huawei-honor-unlock-bootloader#94]
![image](https://user-images.githubusercontent.com/43420467/127117461-c4a76b20-9a11-49be-bd3c-6e59b9a97bc2.png)
Bruteforce is running...
Currently testing code 1000000000000000
Progress: 10.0%
< waiting for any device >
FAILED (remote: 'invalid command')
fastboot: error: Command failed

Could not parse output.
Please check the output above yourself.
If you want to disable this feature, switch variable unknownfail to False

**Comment by DAMcraft** [comment]
![image](https://user-images.githubusercontent.com/43420467/127118051-2674a112-4d13-4fc7-a87a-603ad18f781d.png)
Deactivating the feature gives just a ton of errors

**Comment by AnonymousDebug** [comment]
Are you running EMUI 10?

**Comment by MouseMoosz** [comment]
Please do **NOT** show your IMEI number in public.
