### ISSUE TITLE
Ram usage

### ISSUE THREAD

**Issue by Pedro9700** [SkyEmie/huawei-honor-unlock-bootloader#97]
Is it normal for the program to eat ram like chrome, without showing up as a process in task manager? Memory usage has gone up from 4.3GB to 15GB overnight, but i cant find the process thats using the ram in task manager, and the utilisation only goes down with a reboot of the laptop.

**Comment by AnonymousDebug** [comment]
That's totally not normal, use [ProcessHacker](https://github.com/processhacker/processhacker) to find out whats consuming this much RAM, and this process will be something like "python unlock.py" on windows or similar, it is "python3 unlock.py" on Arch Linux under a shell, under a terminal emulator.
